// タイムラインイベントの型定義
export interface TimelineEvent {
  year: string
  title: string
  description: string
  organization?: string
  date?: string
  details?: string
  isExpanded?: boolean
}

// タブの型定義
export type TimelineTab = 'activities' | 'hackathons' | 'conferences'

// これまでの活動データ
export const activitiesEvents: TimelineEvent[] = [
  {
    year: "2025",
    title: "インターンシップ",
    description: "就業型インターン 1ヶ月",
    organization: "株式会社ヤプリ",
    date: "11月",
    details: "プラットフォーム開発に挑戦し、リポジトリの機能の守備範囲に驚きました。",
    isExpanded: false,
  },
  {
    year: "2025",
    title: "インターンシップ",
    description: "就業型インターン 2週間",
    organization: "チームラボ株式会社",
    date: "10月",
    details: "実際の業務に参加し、設計から実装までを行いました。StateFlowやアーキテクチャの思想を深く理解できました。",
    isExpanded: false,
  },
  {
    year: "2025",
    title: "インターンシップ",
    description: "就業型インターン 1 ヶ月間",
    organization: "合同会社DMM.com",
    date: "8月",
    details: "コンポーネント設計から、テスト、バグ修正まで幅広く学びました。とても勉強になりました。",
    isExpanded: false,
  },
  {
    year: "2025",
    title: "Hackit",
    description: "校内ハッカソン運営",
    date: "8月",
    details: "校内 13 サークルが所属する DevelopHub にて、3 日間開催のハッカソンを主催しました。",
    isExpanded: false,
  },
  {
    year: "2025",
    title: "DeadLine Widgetリリース",
    description: "ハッカソンの作品をリリース",
    date: "6月",
    details: "技育キャンプハッカソンに参加し、DeadLine Widgetをリリースしました。これは、締め切りを管理するためのウィジェットです。",
    isExpanded: false,
  },
  {
    year: "2025",
    title: "バックエンド設計のインターンシップ",
    description: "DB , API 設計に挑戦",
    organization: "株式会社ゆめみ",
    date: "5月",
    details: "DBやAPI設計を学ぶインターンシップに参加。ER図や実践的な設計手法を学びました。",
    isExpanded: false,
  },
  {
    year: "2025",
    title: "長期インターンシップ",
    description: "Streamlit のライブラリ作成に挑戦",
    organization: "KIT 情報処理サービスセンター",
    date: "4月",
    details: "金沢工業大学の長期インターンシップに参加し、PythonやStreamlitを使ったWeb開発に取り組んでいます。",
    isExpanded: false,
  },
  {
    year: "2025",
    title: "長期インターンシップ",
    description: "Goでの大規模開発に挑戦",
    organization: "株式会社ENECHANGE",
    date: "4月",
    details: "ENECHANGEの長期インターンシップに参加し、GoやTypeScriptを使った大規模開発に取り組んでいます。",
    isExpanded: false,
  },
  {
    year: "2025",
    title: "LogiLink開発開始",
    description: "KITHackthonで受賞",
    date: "3月",
    details: "2024物流問題の解決を目指し、SNS型プラットフォームを開発しました。それぞれをネイティブで開発中です。",
    isExpanded: false,
  },
  {
    year: "2025",
    title: "MichikusaMemoリリース",
    description: "IOSアプリ初リリース",
    date: "3月",
    details:
      "位置情報と紐付けて、メモを管理することができるアプリです。SwiftUIで実装し、リリースしました。DBのクラウド化を目指しています。",
    isExpanded: false,
  },
  {
    year: "2025",
    title: "インターンシップ",
    description: "KotlinでAIチャットボットアプリを開発",
    organization: "株式会社CyberAgent",
    date: "2月",
    details: "MVVMやCI/CDなどの技術を学びました。良いメンターさんに巡り会え、とても良い経験になりました。",
    isExpanded: false,
  },
  {
    year: "2025",
    title: "インターンシップ",
    description: "Swiftのチュートリアル",
    organization: "BetaComputing株式会社",
    date: "1月",
    details: "Swiftの基礎を学び、実務のお話を聞くことができました。",
    isExpanded: false,
  },
  {
    year: "2024",
    title: "PresentAI開発",
    description: "プレゼン資料作成アプリ",
    date: "12月",
    details:
      "プレゼン資料を作成する際に、AIが自動でサポートしてくれるアプリです。これを通し、Web開発の基礎を学びました。",
    isExpanded: false,
  },
  {
    year: "2024",
    title: "スマプロ参加",
    description: "校内のプロジェクト活動に参加",
    date: "4月",
    details:
      "ここで初めてアプリ開発に触れ、Androidアプリの開発を学びました。チームでの開発やコードレビューなど、エンジニアとしての基礎を学びました。",
    isExpanded: false,
  },
  {
    year: "2024",
    title: "大学入学",
    description: "金沢工業大学に入学",
    date: "4月",
    details: "情報工学を専攻し、プログラミングの基礎を学び始める",
    isExpanded: false,
  },
]

// ハッカソンデータ
export const hackathonEvents: TimelineEvent[] = [
  {
    year: "2025",
    title: "JPHACKS2025参加",
    description: "日々の料理に革命を 'WinCook'",
    organization: "富士フィルム賞",
    date: "10月",
    details: "両手が汚れている料理中、ウィンクでスクロールを行い、常にレシピを熟知している AI と会話ができる iOS アプリを開発しました。",
    isExpanded: false,
  },
  {
    year: "2025",
    title: "Lovable Hackthon",
    description: "QR ですぐつながる 'Kazarin'",
    date: "8月",
    details: "Lovable を利用し、100%バイブコーディング縛りでのハッカソンでした。supabaseとの連携がスムーズで、UXがとてもよかったです。",
    isExpanded: false,
  },
  {
    year: "2025",
    title: "iOS アプリ開発に挑戦",
    description: "締め切りを絶対に守るアプリ 'Dead Line'",
    date: "5月",
    details: "Widget を利用し、締め切り日時を常に表示してくれるアプリです。SwiftUIで実装し、リリースしました。",
    isExpanded: false,
  },
  {
    year: "2025",
    title: "ローカル LLM 搭載デスクトップアプリ",
    description: "日々の人生をドラマチックに 'EpicLog'",
    date: "4月",
    details: "ローカルLLMがPCの履歴を読み取り、ドラマチックな日記を出力してくれます。Qwenをローカルで使用しているため、チューニングに苦労しました。",
    isExpanded: false,
  },
  {
    year: "2025",
    title: "初ソロハッカソン！！",
    description: "エンジニアロードマップ 'DevTree'",
    date: "3月",
    details: "エンジニアのスキルやロードマップをアプリに落とし込みました。スキルツリー状になっており、自分が達成した箇所を設定することができます。",
    isExpanded: false,
  },
  {
    year: "2025",
    title: "KIT Hackathon 参加",
    description: "物流を DX 化 'LogiLink'",
    organization: "新人賞・8番ラーメン賞",
    date: "3月",
    details: "物流2025年問題の解決のため、サプライチェーンを可視化するアプリを開発しました。Web アプリだけでなく、Android アプリも開発しました。",
    isExpanded: false,
  },
  {
    year: "2025",
    title: "Engineer Guild Hackathon 参加",
    description: "日報SNS 'キロクル'",
    date: "2月",
    details: "日報を投稿し合う SNS です。1 週間で実際に利用できる状態まで実装し、アプリとしての完成度を追求しました。",
    isExpanded: false,
  },
  {
    year: "2025",
    title: "Android × Camera",
    description: "写真で撮るだけ家計簿 'おさいふカメラ'",
    date: "2月",
    details: "写真を撮るだけで家計簿を管理できるアプリです。ネイティブならではの機能を搭載し、MVVMで堅牢なアーキテクチャで実装されています。",
    isExpanded: false,
  },
  {
    year: "2024",
    title: "Android と LLM の融合",
    description: "自分だけの Vtuber 'AIVY'",
    organization: "努力賞",
    date: "12月",
    details: "Vtuber の中身を AI にし、Android アプリで会話をすることができるアプリです。LLM と Android を連携させ、カスタマイズ性の高い AI の Vtuber を作成できます。",
    isExpanded: false,
  },
  {
    year: "2024",
    title: "目指せ Canva !!",
    description: "AI 搭載 Canva 'PresentsAI'",
    date: "12月",
    details: "1 年生のみのチームで打倒 Canva を目指して開発しました。発表途中に AI がアシストしてくれる機能や、最後に点数をつけてくれる機能など、盛りだくさんのアプリです。",
    isExpanded: false,
  },
  {
    year: "2024",
    title: "スマプロハッカソン",
    description: "ペット育成アプリ'VirtuPet'",
    organization: "優秀賞",
    date: "11月",
    details: "初めての 1 年生のみチームでのハッカソンでリーダーを努めました。デスクトップ画面に Unity で動かしているペットをリアルタイムで表示し、育成するアプリです",
    isExpanded: false,
  },
  {
    year: "2024",
    title: "JPHACKS2024参加",
    description: "運動促進アプリ 'ShareFit'",
    date: "10月",
    details: "全国規模のオフラインのハッカソンに初めて参加しました。本格的な Android アプリを初めて開発し、学ぶことができました。",
    isExpanded: false,
  },
  {
    year: "2024",
    title: "ゲーム開発に挑戦",
    description: "コンビニ経営ゲーム '店長になろう'",
    organization: "努力賞",
    date: "9月",
    details: "DxLib を利用し、店長視点での経営ゲームを開発しました。お客さんのアルゴリズムや C# によるプログラミングを学びました。",
    isExpanded: false,
  },
  {
    year: "2024",
    title: "人生初のハッカソン",
    description: "アルバム生成アプリ '思い出花火'",
    date: "9月",
    details: "React と Firebase を利用し、複数人が持ち寄った写真からアルバムを作成するアプリを開発しました。",
    isExpanded: false,
  },
]

// カンファレンスデータ
export const conferenceEvents: TimelineEvent[] = [
  {
    year: "2025",
    title: "アーキテクチャカンファレンス",
    description: "アーキテクチャが集う 2 日間！！",
    date: "11月",
    details: "各社のクラウドアーキテクチャを拝見し、憧れの Gregor Hohpe さんにお会いすることができました。",
    isExpanded: false,
  },
  {
    year: "2025",
    title: "Kotlin Fest",
    description: "Kotlin の祭りに参加！！",
    date: "11月",
    details: "想像以上にバックエンド Kotlin の勢いが強く、言語仕様の理解の甘さを痛感しました。",
    isExpanded: false,
  },
  {
    year: "2025",
    title: "Vue Fes",
    description: "初心者だけど、Vue Fest に参加しました！！",
    date: "10月",
    details: "ほぼ触ったことがなかったですが、React との違いや Vue の最新動向を知ることができました。",
    isExpanded: false,
  },
  {
    year: "2025",
    title: "Go Conference",
    description: "勢いに乗っている Go のカンファレンス！！",
    date: "9月",
    details: "Go の用途の幅の広さや、魅力の大部分である、並行処理の内部実装を理解できました。",
    isExpanded: false,
  },
  {
    year: "2025",
    title: "iOSDC",
    description: "待ちに待った Android カンファレンス !!",
    date: "9月",
    details: "Android のカンファレンスに初参加。インターンで学んだ技術の発展的な内容や、知人との交流を通して、Android の技術をキャッチアップしました。",
    isExpanded: false,
  },
  {
    year: "2025",
    title: "Droid Kaigi",
    description: "待ちに待った Android カンファレンス !!",
    date: "9月",
    details: "Android のカンファレンスに初参加。インターンで学んだ技術の発展的な内容や、知人との交流を通して、Android の技術をキャッチアップしました。",
    isExpanded: false,
  },
  {
    year: "2025",
    title: "AWS Summit",
    description: "クラウド技術のキャッチアップ",
    date: "6月",
    details: "AWS の技術や Amazon の Bedrock を利用した AI の技術を学びました。クラウド運用の熱量がとても上がりました。",
    isExpanded: false,
  },
  {
    year: "2025",
    title: "Interop Tokyo",
    description: "通信やセキュリティなどの低レイヤー技術のキャッチアップ",
    date: "6月",
    details: "各企業の取り組みや製品を見る、現場のエンジニアに聞くことで、技術の深さを感じることができました。",
    isExpanded: false,
  },
  {
    year: "2025",
    title: "TS Kaigi",
    description: "Web のカンファレンスに参加！！",
    date: "5月",
    details: "TypeScript の勢いに触れ、とても刺激的な体験をしました。また、学生支援の方々とも交流するなど、貴重な体験をしました。",
    isExpanded: false,
  },
  {
    year: "2025",
    title: "TrySwift !!",
    description: "iOS の国内最大イベントに参加しました。",
    date: "4月",
    details: "BuriKaigi を機に iOS 開発を始め、TrySwift に参加しました。現場のエンジニアやブースの方々と交流してきました。",
    isExpanded: false,
  },
  {
    year: "2024",
    title: "BuriKaigi",
    description: "人生初のカンファレンス。富山で鰤しゃぶをいただきました。",
    date: "2月",
    details: "技術問わず、様々な分野の知見を得ることができました。ブリめっちゃ美味しかったです。",
    isExpanded: false,
  },
]

// タブごとのデータマッピング
export const timelineData = {
  activities: activitiesEvents,
  hackathons: hackathonEvents,
  conferences: conferenceEvents,
}
